# This workflow creates docker container from hcrystalball repository including jupyter
# enabling fast start-up when launching binder to interactively explore code examples
# from https://github.com/jupyterhub/repo2docker-action#use-github-actions-to-cache-the-build-for-binderhub
name: Build Binder Notebook Container

on:
  push:
    branches:
    - main

jobs:
  Create-MyBinderOrg-Cache:
    runs-on: ubuntu-latest
    steps:
    - name: cache binder build on mybinder.org
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }} # This builds the container on mybinder.org with the branch that was pushed on.
